save-visualization: true

directory:
  checkpoint: ../checkpoint/yuhsi_ViTB16_val_98.73_test_98.64.bin
  data:
    root-dir: ../../data/crop_data/data/
    path-csv: ../../data/crop_data/seperate_csv/fold1_train.csv
  output:
    root-dir: ../output/fold1_train_atten
    sub-dir-vis: visualization
    sub-dir-attention-map: attention-map

train:
  attention-method: grad-CAM
  index-start: 56000
  index-end: -1
  model:
    type: ViT-B_16 # Choose from ["ViT-B_16", "ViT-B_32", "ViT-L_16", "ViT-L_32", "ViT-H_14", "R50-ViT-B_16"]
  img-size: 384
  device: cuda