output:
  output_folder: 'results/fold1_real'
  description: Unet-Mish-ch64-4^3*3*2

keep_train: true
path_pretrained_weight: /work/kevin8ntust/ViT-Crop-Recognition/AttentionCrop/results/Unet-Mish-ch64-4^3*3*2/iteration_89000.pth
keep_train_obj: ['model', 'optimizer', 'lr_scheduler']  # ['model', 'optimizer', 'lr_scheduler']

train:
  batch_size: 1
  total_iterations: 111000
  eval_freq: 10000
  save_model_freq: 1000
  lr_scheduler: 
    sched: cosine
    warmup_iterations: 3332
    warmup_lr: 0.000001
    min_lr: 0.00001
  optimizer: 
    mode: adamW
    lr: 0.00025
    weight_decay: 0.1
val:
  batch_size: 1
data:
  classification_model_resolution: 384
  root_dataset_img: ../../data/crop_data/data/
  root_dataset_attn: ../output/attention/attention-map/
  path_csv_train: ../../data/crop_data/seperate_csv/fold1_train.csv
  path_csv_val: ../../data/crop_data/seperate_csv/fold1_val_test.csv
  format_attn: '.dat'
model:
  list_downsample_rate: [4, 4, 4, 3, 2]
  hidden_activation: Mish # Select from ["LeackyReLU", "Mish"]
test:
  checkpoint: /work/kevin8ntust/ViT-Crop-Recognition/AttentionCrop/results/Unet-ch64-4^3*3*2/iteration_100000.pth
  path_csv_test: ./fold1_test_toy.csv
  visualization_downsample_rate: 4 # If visualization_downsample_rate is set to 4, the visualization size will be a quarter of the original.
  original_img_ratio_difference_map: 0.4
  original_img_ratio_correctness_map: 0.7
  do_visualization: true
  output:
    folder: test_results
    description: Unet-ch64-4^3*3*2-100000
  
